crud/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('operations.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

operations/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.form_init,name="index"),
    path('save/',views.save_form,name="save"),
    path('del/',views.delete_data,name="del"),
    path('edit/',views.edit_data,name="edit"),

]

operations/models.py
from django.db import models
from django.core import validators
from django import forms
# Create your models here.
class Student(models.Model):
    def checknumber(value):
        if len(str(value)) !=10:
            raise forms.ValidationError("Entered incorrect mobile number")
        

    student_field = (
        ('BIT','BIT'),
        ('BBA','BBA'),
        ('MSCIT','MSCIT'),
        ('CSIT','CSIT')
    )
    full_name = models.CharField(max_length=70,help_text="Enter your full name",error_messages={'required':'You cannot leave name field empty'})
    address = models.CharField(max_length=70)
    phone_number = models.IntegerField(validators=[checknumber],help_text="Your number must contain 10 digits")
    field = models.CharField(max_length=70,choices=student_field,default='BIT')
    picture = models.ImageField(upload_to='images/')

operations/forms.py
from django import forms
from django.forms import fields, widgets
from . models import Student 
class StudentForm(forms.ModelForm):
    class  Meta:
        model = Student
        fields = ['full_name','address','phone_number','field','picture']
        widgets = {
            'full_name' :forms.TextInput(attrs={'placeholder':'Suman Raj Khanal','class':'form-control','required':True}),
            'phone_number':forms.NumberInput(attrs={'placeholder':'9803955983','class':'form-control'}),
            'address':forms.TextInput(attrs={'placeholder':'Thali,Kathmandu','class':'form-control'}),
            'field':forms.Select(attrs={'class':'form-control'}),
            
        }

operations/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from .forms import StudentForm
from django.http import HttpResponseRedirect
from . models import Student

# Create your views here.
def form_init(request):
    form = StudentForm()
    student = Student.objects.all()
    return render (request, 'html/index.html',{'form':form,'student':student})

def save_form(request):
    form = StudentForm(request.POST or None,request.FILES or None)
    if request.is_ajax():
        if form.is_valid():
            sid = request.POST.get('student_id')
            if (sid==""):
                std_id = Student(full_name= request.POST['full_name'],address = request.POST['address'],phone_number = request.POST['phone_number'],field= request.POST['field'],picture= request.FILES['picture'])
            else:
                std_id = Student(id =int(sid),full_name= request.POST['full_name'],address = request.POST['address'],phone_number = request.POST['phone_number'],field= request.POST['field'],picture= request.FILES['picture'])
            std_id.save()
            all_data = Student.objects.values()
            print(all_data)
            return JsonResponse({'process':'done','all_data':list(all_data)})
        else:
            error_list = form.errors.as_data()
            error_list_name = []
            error_list_value = []

            for i in error_list.keys():
                error_list_name.append(i)
                
                for j in error_list[i][0]:
                    error_list_value.append(j)
            return JsonResponse({'error_name':error_list_name,'error_value':error_list_value})
    else:
        return JsonResponse({'process':'error'})


def delete_data(request):
    if request.method == 'GET':
        id = int(request.GET.get('id'))
        dt = Student.objects.get(id=id)
        dt.delete()
        return JsonResponse({"result":"success"})
    else:
        return JsonResponse({"result":"failed"})
        

def edit_data(request):
    if request.method == "POST":
        print("suman")
        print(request.POST.get('id'))
        dt = Student.objects.get(id=int(request.POST.get('id')))
        full_name = dt.full_name
        address = dt.address
        phone_number = dt.phone_number
        field = dt.field
        img = dt.picture
        id = dt.id
        print(img)
        return JsonResponse({'result':1,'full_name':full_name,'address':address,'phone_number':phone_number,'field':field,'img':str(img),'id':id})
    else:
        return JsonResponse({"result":0})

operations/templates/html/ajax_.html
$(document).ready(function(){
const img  = document.getElementById('id_picture')
var url =""
img.addEventListener('change',()=>{
    url = URL.createObjectURL(img.files[0])
    document.getElementById('show_img').innerHTML = `<img  src="${url}" width= 100>`
    console.log(url)
})

{% comment %} Inserting Student data {% endcomment %}
$('#save').click('submit',e=>{
    e.preventDefault();
    data = {}
    var form_data = $('form').serializeArray()
    
    $.each(form_data,(index,value)=>{
        data[value['name']] = value['value']
    })
    console.log(data)
    console.log()
    const df = new FormData();
    df.append('csrfmiddlewaretoken',data['csrfmiddlewaretoken'])
    df.append('address',data['address'])
    df.append('field',data['field'])
    df.append('full_name',data['full_name'])
    df.append('phone_number',data['phone_number'])
    df.append('picture',img.files[0])
    df.append('student_id',$('#student_id').val())

    $.ajax({
        type:'POST',
        url: {% url 'save' %},
        enctype: 'multipart/form',
        data:df,
        success:function(data){
            var error_list_data = {}
            console.log(data.error_name)
            $.each(data.error_name,(k,v)=>{
                error_list_data[v] = data.error_value[k]
            })

            if (error_list_data['full_name']){
                $('#full_name_error').html(error_list_data['full_name'])
            }else{
                $('#full_name_error').html('')

            }

            if (error_list_data['address']){
                $('#address_error').html(error_list_data['address'])
            }else{
                $('#address_error').html('')
            }

            if (error_list_data['phone_number']){
                $('#phone_number_error').html(error_list_data['phone_number'])
            }else{
                $('#phone_number_error').html('')
            }

            if (error_list_data['picture']){
                $('#picture_error').html(error_list_data['picture'])
            }else{
                $('#picture_error').html('')
            }
            if (data.process == 'done'){
                var txt = `<div class="alert alert-info alert-dismissible fade show" role="alert">
                Student Data is saved successfully!!</div>`
                $('#data-success').delay(5000).fadeOut('slow');
                $('#data-success').html(txt)
                $('#form_data')[0].reset();
                $('#show_img').html('')
                std = data.all_data
                output = ""
                for(i=0;i<std.length;i++){
                    output+= `<tr>
                <th scope="row">${std[i].id}</th>
                <td>${std[i].full_name}</td>
                <td>${std[i].address}</td>
                <td>${std[i].phone_number}</td>
                <td>${std[i].field}</td>
                <td>
                <input class="btn-sm btn-info text-white edit-btn"  type="button" data-sid ="${std[i].id}" value="Edit">
                <input class="btn-sm btn-danger text-white del-btn"  type="button" data-sid ="${std[i].id}" value="Delete">
                </td>
                </tr>`
                }
                $('#table_body').html(output)
                {% comment %} clearning the student_id {% endcomment %}
                $('#student_id').val("")
            }     
            
        },
        error:function(error){
            console.log("error")
        },
        cache:false,
        contentType: false,
        processData:false
    })
})


{% comment %} Deleting Student Record {% endcomment %}
$("tbody").on("click",".del-btn",function(){
    console.log("clicked")
    click = this;
    var id = $(click).attr("data-sid");
    console.log(id)
    data = {'id':id}
    $.ajax({
        method:"GET",
        url: {% url 'del' %},
        data: data,
        success:(data)=>{
            console.log("success",data)
            if (data.result == "success"){
            var txt = `<div class="alert alert-danger alert-dismissible fade show" role="alert">
            Student Data is deleted successfully!!</div>`
            $(click).closest("tr").fadeOut();
            $('#data-success').delay(5000).fadeOut('slow');
                $('#data-success').html(txt)

            }else{
            var txt = `<div class="alert alert-warning alert-dismissible fade show" role="alert">
            Student Data is cannot be deleted!!</div>`

            $('#data-success').delay(5000).fadeOut('slow');
                $('#data-success').html(txt)

            }
            
        },

    })
})

{% comment %} Edit Student Record {% endcomment %}
$("tbody").on("click",".edit-btn",function(){
    console.log("clicked")
    click = this;
    var id = $(click).attr("data-sid");
    console.log(id)
    var csrf = $("input[name=csrfmiddlewaretoken]").val()
    console.log(csrf)
    data = {id:id,csrfmiddlewaretoken:csrf}
    $.ajax({
        method:"POST",
        url: {% url 'edit' %},
        data: data,
        success:(data)=>{
            console.log(data)
            if (data.result == 1){
                console.log(data.full_name)
                console.log(data.img)
                var src = "media/"+data.img
                console.log(src)
                var img = `<img src=${src} width=100>`
                $("#show_img").html(img)
                $("#id_full_name").val(data.full_name);
                $("#id_address").val(data.address);
                $("#id_phone_number").val(data.phone_number);
                $("#id_field").val(data.field);
                $("#student_id").val(data.id)

            }else{
          

            }
            
        },

    })
})


})

operations/templates/html/index.html
{% extends 'core.html' %}
{% load static %}
{% block title %}CRUD{% endblock title %}
{% block top %}
<div class="container">
    <h3 class="text-center p-3 mt-1 text-white" style="background-color: #084298;">Employee Details record</h5>
        <div class="row">
            <div class="col-md-5">
                <h3 class="bg-info p-2 text-center mt-3">Employee</h3>
                <div id="data-success"></div>
                {% include 'html/show_form.html' %}
                {% for er in form.non_field_errors %}
                {{er}}
                {% endfor %}
            </div>


            <div class="col-md-7">
                <h3 class="bg-info p-2 text-center mt-3">Employee Record</h3>
                <div style="height:auto;width:auto">
                    {% include 'html/table.html' %}
                </div>
            </div>



        </div>
</div>
{% endblock top %}


{% comment %} JavaScript Block {% endcomment %}
{% block js %}

{% include 'html/ajax_.html' %}

{% endblock js %}

operations/templates/html/show_form.html
<form id="form_data" action="" method="post" novalidate enctype="multipart/form-data">
{% csrf_token %}
<input type="hidden" id="student_id" name="student_id" value="">
{% comment %} Full Name {% endcomment %}
<h5>{{form.full_name.label}}</h5>
{{form.full_name}}
<small class="text-muted">{{form.full_name.help_text}}</small><br>
<span id = "full_name_error" class="fst-italic text-danger">{{form.full_name.errors|striptags}}</span>
<br>


{% comment %} Address {% endcomment %}
<h5>{{form.address.label}}</h5>
{{form.address}}
<span id="address_error" class="fst-italic text-danger">{{form.address.errors|striptags}}</span>

{% comment %} Phone Number {% endcomment %}
<h5>{{form.phone_number.label}}</h5>
{{form.phone_number}}
<small class="text-muted">{{form.phone_number.help_text}}</small><br>
<span id="phone_number_error" class="fst-italic text-danger">{{form.phone_number.errors|striptags}}</span>

{% comment %} Choice {% endcomment %}
<h5>{{form.field.label}}</h5>
{{form.field}}

{% comment %} Picture {% endcomment %}

<h5>{{form.picture.label}}</h5>
{{form.picture}} <br>
<span id="picture_error" class="fst-italic text-danger">{{form.picture.errors|striptags}}</span>

<br>
<div id="show_img"></div>
<input class="btn btn-success mt-3" id="save" type="submit" value="Save">
</form>

operations/templates/html/table.html
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Full Name</th>
      <th scope="col">Address</th>
      <th scope="col">Number</th>
      <th scope="col">Field</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody id="table_body">
    {% for data in student %}
    <tr>
      <th scope="row">{{data.id}}</th>
      <td>{{data.full_name}}</td>
      <td>{{data.address}}</td>
      <td>{{data.phone_number}}</td>
      <td>{{data.field}}</td>
      <td>
        <input class="btn-sm btn-info text-white edit-btn" style="width: 60px;" type="button" data-sid="{{data.id}}"
          value="Edit">
        <input class="btn-sm btn-danger text-white del-btn" style="width: 60px; margin-top: 2px;" type=" button"
          data-sid="{{data.id}}" value="Delete">
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

templates/core.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/core.css' %}" />

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block top %} {% endblock top %} {% block content %}{% endblock content %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
  
    {% comment %} Javascript Block {% endcomment %}
    <script>
    
      {% block js %}

      {% endblock js %}
    </script>
  </body>
</html>